export const SET_QUESTIONS_SUCCESS = "SET_QUESTIONS_SUCCESS";
export const SET_INDEX_SUCCESS = "SET_INDEX_SUCCESS";
export const SET_CURRENT_QUESTION_SUCCESS = "SET_CURRENT_QUESTION";
export const SET_CHOICES_SUCCESS = "SET_CHOICES_SUCCESS";
export const SET_SLICED_CHOICES_SUCCESS = "SET_SLICED_CHOICES_SUCCESS";
